name: api

on: push

jobs:
  test:
    runs-on: ['ubuntu-latest']
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: GitHub Action for Homebrew
      uses: artemnovichkov/action-homebrew@0.1.0
    - name: Install oauth2l
      run: brew install oauth2l
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./web/api 
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        VALID_TOKEN: ${{ secrets.VALID_TOKEN }}
